apiVersion: v1
kind: LimitRange
metadata:
  name:
  namespace:
spec:
  limits:
  - type: Pod 
    max:
      cpu: "1"
      memory: "1Gi"
  - type: Container 
    default:
      cpu: "1"
      memory: "1Gi"
    defaultRequest:
      cpu: "50"
      memory: "512Mi"
    max:
      cpu: 1
      memory: 1Gi
    
