apiVersion: v1
kind: LimitRange
metadata:
  name:
  namespace:
spec:
  limits:
  - type: Pod 
    max:
      cpu:
      memory:
  - type: Container 
    default:
      cpu:
      memory:
    defaultRequest:
      cpu:
      memory:
    max:
      cpu:
      memory:
    
